### ISSUE TITLE
Kernel 4.19 build issue

### ISSUE THREAD

**Issue by vladest** [rockchip-linux/meta-rockchip#58]
during kernel 4.19 build got error that "./scripts/io-domain.sh" not found
suggested fix:
replace line 227 in mkimg to
	${srctree}/scripts/io-domain.sh ${srctree}/arch/arm64/boot/dts/rockchip/.${DTB}
instead of:
	./scripts/io-domain.sh ${srctree}/arch/arm64/boot/dts/rockchip/.${DTB}

**Comment by JeffyCN** [comment]
this is a knowing issue caused by using relative path in scripts/mkimg.

fixed recently by:
commit 7dd3d860213ab8c305d0c362f49670e2364ec7d6
Author: Caesar Wang <wxt@rock-chips.com>
Date:   Tue Sep 7 17:02:54 2021 +0800

    scripts/mkimg: fixes the realpath for io-domain.sh

--- a/scripts/mkimg
+++ b/scripts/mkimg
@@ -224,7 +224,7 @@ fi
 scripts/resource_tool ${DTB_PATH} ${LOGO} ${LOGO_KERNEL} >/dev/null

 if [ "${ARCH}" == "arm64" ]; then
-       ./scripts/io-domain.sh ${srctree}/arch/arm64/boot/dts/rockchip/.${DTB}
+       ${srctree}/scripts/io-domain.sh ${srctree}/arch/arm64/boot/dts/rockchip/.${DTB}
 fi

 echo "  Image:  resource.img (with ${DTB} ${LOGO} ${LOGO_KERNEL}) is ready"
